//
//	This file was generated by the GEOS Resource Compiler
//
//	DO NOT EDIT! Any changes will be lost!
//
//	Edit proper resource file instead.
//

void mnu_geos_geosInfo (void);
void mnu_geos_desktopInfo (void);
void mnu_geos_selectPrinter (void);
void mnu_geos_selectInput (void);

const void geosMenu = {
	(char)15, (char)71,
	(int)0, (int)62,
	(char)(4 | VERTICAL),
	"GEOS info", (char)MENU_ACTION, (int)mnu_geos_geosInfo,
	"desktop info", (char)MENU_ACTION, (int)mnu_geos_desktopInfo,
	"select printer", (char)MENU_ACTION, (int)mnu_geos_selectPrinter,
	"select input", (char)MENU_ACTION, (int)mnu_geos_selectInput,
};

void mnu_file_open (void);
void mnu_file_duplicate (void);
void mnu_file_rename (void);
void mnu_file_info (void);
void mnu_file_print (void);
void mnu_file_delete (void);
void mnu_file_undodelete (void);

const void fileMenu = {
	(char)15, (char)113,
	(int)30, (int)88,
	(char)(7 | VERTICAL),
	"open", (char)MENU_ACTION, (int)mnu_file_open,
	"duplicate", (char)MENU_ACTION, (int)mnu_file_duplicate,
	"rename", (char)MENU_ACTION, (int)mnu_file_rename,
	"info", (char)MENU_ACTION, (int)mnu_file_info,
	"print", (char)MENU_ACTION, (int)mnu_file_print,
	"delete", (char)MENU_ACTION, (int)mnu_file_delete,
	"undo delete", (char)MENU_ACTION, (int)mnu_file_undodelete,
};

void mnu_view_byicon (void);
void mnu_view_bysize (void);
void mnu_view_bytype (void);
void mnu_view_bydate (void);
void mnu_view_byname (void);

const void viewMenu = {
	(char)15, (char)85,
	(int)50, (int)95,
	(char)(5 | VERTICAL),
	"by icon", (char)MENU_ACTION, (int)mnu_view_byicon,
	"by size", (char)MENU_ACTION, (int)mnu_view_bysize,
	"by type", (char)MENU_ACTION, (int)mnu_view_bytype,
	"by date", (char)MENU_ACTION, (int)mnu_view_bydate,
	"by name", (char)MENU_ACTION, (int)mnu_view_byname,
};

void mnu_disk_open (void);
void mnu_disk_close (void);
void mnu_disk_rename (void);
void mnu_disk_copy (void);
void mnu_disk_validate (void);
void mnu_disk_erase (void);
void mnu_disk_format (void);

const void diskMenu = {
	(char)15, (char)113,
	(int)77, (int)117,
	(char)(7 | VERTICAL),
	"open", (char)MENU_ACTION, (int)mnu_disk_open,
	"close", (char)MENU_ACTION, (int)mnu_disk_close,
	"rename", (char)MENU_ACTION, (int)mnu_disk_rename,
	"copy", (char)MENU_ACTION, (int)mnu_disk_copy,
	"validate", (char)MENU_ACTION, (int)mnu_disk_validate,
	"erase", (char)MENU_ACTION, (int)mnu_disk_erase,
	"format", (char)MENU_ACTION, (int)mnu_disk_format,
};

void mnu_select_allpages (void);
void mnu_select_pagefiles (void);
void mnu_select_borderfiles (void);

const void selectMenu = {
	(char)15, (char)57,
	(int)101, (int)156,
	(char)(3 | VERTICAL),
	"all pages", (char)MENU_ACTION, (int)mnu_select_allpages,
	"page files", (char)MENU_ACTION, (int)mnu_select_pagefiles,
	"border files", (char)MENU_ACTION, (int)mnu_select_borderfiles,
};

void mnu_page_append (void);
void mnu_page_delete (void);

const void pageMenu = {
	(char)15, (char)43,
	(int)133, (int)170,
	(char)(2 | VERTICAL),
	"append", (char)MENU_ACTION, (int)mnu_page_append,
	"delete", (char)MENU_ACTION, (int)mnu_page_delete,
};

void mnu_options_setclock (void);
void mnu_options_reset (void);
void mnu_options_basic (void);
void mnu_options_shortcuts (void);

const void optionsMenu = {
	(char)15, (char)71,
	(int)161, (int)208,
	(char)(4 | VERTICAL),
	"set clock", (char)MENU_ACTION, (int)mnu_options_setclock,
	"RESET", (char)MENU_ACTION, (int)mnu_options_reset,
	"BASIC", (char)MENU_ACTION, (int)mnu_options_basic,
	"shortcuts", (char)MENU_ACTION, (int)mnu_options_shortcuts,
};


const void mainMenu = {
	(char)0, (char)15,
	(int)0, (int)199,
	(char)(7 | HORIZONTAL),
	"geos", (char)SUB_MENU, (int)&geosMenu,
	"file", (char)SUB_MENU, (int)&fileMenu,
	"view", (char)SUB_MENU, (int)&viewMenu,
	"disk", (char)SUB_MENU, (int)&diskMenu,
	"select", (char)SUB_MENU, (int)&selectMenu,
	"page", (char)SUB_MENU, (int)&pageMenu,
	"options", (char)SUB_MENU, (int)&optionsMenu,
};

